apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: conversor-web
  template:
    metadata:
      labels:
        app: conversor-web
    spec:
      containers:
      - name: site
        image: caiocof/aula-01-devops-elite:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: conversor-web
spec:
  selector:
    app: conversor-web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
